### ISSUE TITLE
Readable error messages for syntax errors

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#124]
Currently, it's difficult to tell what is wrong with the syntax. Example:

    /Users/stuhlmueller/Projects/webppl/src/transforms/cps.js:167
      switch (node.type) {
                  ^
    TypeError: Cannot read property 'type' of null
        at cps (/Users/stuhlmueller/Projects/webppl/src/transforms/cps.js:167:15)
        at Array.<anonymous> (/Users/stuhlmueller/Projects/webppl/src/transforms/cps.js:308:14)
        at Array.<anonymous> (/Users/stuhlmueller/Projects/webppl/src/syntax.js:30:27)
        at loop (/Users/stuhlmueller/Projects/webppl/src/syntax.js:50:24)
        at /Users/stuhlmueller/Projects/webppl/src/syntax.js:51:16
        at Array.<anonymous> (/Users/stuhlmueller/Projects/webppl/src/syntax.js:35:16)
        at loop (/Users/stuhlmueller/Projects/webppl/src/syntax.js:50:24)
        at /Users/stuhlmueller/Projects/webppl/src/syntax.js:51:16
        at Array.<anonymous> (/Users/stuhlmueller/Projects/webppl/src/syntax.js:35:16)
        at loop (/Users/stuhlmueller/Projects/webppl/src/syntax.js:50:24)

**Comment by stuhlmueller** [comment]
This has improved as a side-effect of our use of `sweet.js`. I'm going to close this for now—if anyone gets obscure syntax errors, feel free to reopen.
