### ISSUE TITLE
CPS transform doesn't allow object literal as return value of program

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#262]
This code:
````
var foo = function() {
	return gaussian(0, 1);
}
{ val: foo() };
````
gives this error:
````
{ type: 'LabeledStatement',
  label: { type: 'Identifier', name: 'val' },
  body: 
   { type: 'ExpressionStatement',
     expression: 
      { callee: [Object],
        arguments: [Object],
        loc: null,
        type: 'CallExpression',
        comments: null } } }
cpsFinalStatement
/Users/dritchie/Git/webppl-vpf/src/syntax.js:20
    throw new Error(message);
          ^
Error: cpsFinalStatement
    at /Users/dritchie/Git/webppl-vpf/src/syntax.js:20:11
    at match (/Users/dritchie/Git/webppl-vpf/src/syntax.js:52:10)
    at cpsFinalStatement (/Users/dritchie/Git/webppl-vpf/src/transforms/cps.js:291:10)
    at cpsSequence (/Users/dritchie/Git/webppl-vpf/src/transforms/cps.js:244:12)
    at Array.<anonymous> (/Users/dritchie/Git/webppl-vpf/src/transforms/cps.js:254:14)
    at Array.<anonymous> (/Users/dritchie/Git/webppl-vpf/src/syntax.js:30:27)
    at match (/Users/dritchie/Git/webppl-vpf/src/syntax.js:47:27)
    at cpsInnerStatement (/Users/dritchie/Git/webppl-vpf/src/transforms/cps.js:252:10)
    at cpsSequence (/Users/dritchie/Git/webppl-vpf/src/transforms/cps.js:247:12)
    at cpsSequence (/Users/dritchie/Git/webppl-vpf/src/transforms/cps.js:247:40)
````
It looks like the object literal is being mis-parsed as a Labeled Statement.

**Comment by null-a** [comment]
Interesting!

In JS `{ val: foo() }` can be parsed as either an expression or a statement depending on context. In this case, it's parsed as a statement composed of a labeled statement within a block.

Wrapping the last line in parens will cause it to be parsed as an expression:

````js
var foo = function() {
  return gaussian(0, 1);
};
({ val: foo() });
````

The semi-colon after the function is now significant, otherwise it's function invocation. If we fix this by inserting the parens automatically, we'd have to watch out for that. Perhaps there's a nicer way.
