### ISSUE TITLE
IncrementalMH doesn't work with globalStore

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#311]
Running this model (with latest dev version b5eaaf9):

```js
var addToGlobalStore = function(x) {
  globalStore.foo += x;
}

var model = function() {
  globalStore.foo = 0;
  var a = gaussian(0,1);
  addToGlobalStore(a);

  var b = beta(1,1);
  addToGlobalStore(b);

  return [a,b]
}

IncrementalMH(model, 100)
```

Gives this error:

```
/Users/long/webppl/src/inference/incrementalmh.js:258
      if (s1[prop] !== s2[prop])
            ^

TypeError: Cannot read property 'foo' of undefined
    at storesEqual (/Users/long/webppl/src/inference/incrementalmh.js:258:13)
    at FunctionNode.registerInputChanges (/Users/long/webppl/src/inference/incrementalmh.js:457:10)
    at IncrementalMH.cachelookup (/Users/long/webppl/src/inference/incrementalmh.js:977:19)
    at IncrementalMH.incrementalize (/Users/long/webppl/src/inference/incrementalmh.js:950:19)
    at env.incrementalize (/Users/long/webppl/src/header.js:107:26)
    at /Users/long/webppl/tmp.js:1305:44
    at runTrampoline (/Users/long/webppl/tmp.js:22:17)
    at /Users/long/webppl/tmp.js:27:9
    at Object.<anonymous> (/Users/long/webppl/tmp.js:1335:1)
    at Module._compile (module.js:435:26)
```

The problematic function is `storesEqual` in *`incrementalmh.js`*:

```js
  function storesEqual(s1, s2) {
    var prop;
    for (prop in s1) {
      if (s1[prop] !== s2[prop])
        return false;
    }
    for (prop in s2) {
      if (s1[prop] !== s2[prop])
        return false;
    }
    return true;
  }
```

The issue is that `s1` is undefined. I think adding this check at the very beginning of the function would help:

```js
if (s1 === undefined) {
  return (s2 === undefined)
}
```

But I don't really know how incrementalization works, so I'm not sure if this fix is appropriate.

**Comment by longouyang** [comment]
I'm on 2ac00c9, which includes Daniel's fix, but I still get that `Cannot read property 'foo' of undefined` error

**Comment by dritchie** [comment]
Can anybody else confirm? I just double-checked 2ac00c9 on my machine, and everything checks out fine.

**Comment by null-a** [comment]
I can run the original example without error on 2ac00c9.

**Comment by longouyang** [comment]
Ah, something weird happened with my git repo where I thought it had pulled down the latest changes but it hadn't. Yes, 2ac00c9 works for me too.
