### ISSUE TITLE
Cannot find module './inference/enumerate'

### ISSUE THREAD

**Issue by jsalvatier** [probmods/webppl#391]
#390 seems to have caused a bundling problem. 

If I revert #390, this succeeds.

```
➜  webppl git:(dev) ✗ grunt bundle
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?

Running "bundle" task

Running "browserify" task
Error: Cannot find module './inference/enumerate' from '/Users/jsalvatier/workspace/webppl/src'
    at /Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
Warning: Command failed: browserify -t [./src/bundle.js] -g brfs src/browser.js -o bundle/webppl.js
Error: Cannot find module './inference/enumerate' from '/Users/jsalvatier/workspace/webppl/src'
    at /Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/jsalvatier/npm/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
 Use --force to continue.

Aborted due to warnings.
```

**Comment by null-a** [comment]
Hi John, bundling the dev branch is working for me. Also, we have a few tests which will fail if bundling doesn't work, and CI passed for #390, so I'm confused about why reverting that is helping. Ignoring that for now... `src/inference/enumerate.js` only exists after `enumerate.ad.js` is transformed by expanding ad macros. If it's missing (as the error suggests), it seems likely that this transform hasn't happened. Did you run `npm install` after fetching the most recent commits? If not, could you try doing so?

**Comment by jsalvatier** [comment]
Pulling, `npm install`ing then bundling, seems to have fixed the problem. 

Thanks!
