### ISSUE TITLE
Uninformative error messages when using arrays instead of Tensors

### ISSUE THREAD

**Issue by jayelm** [probmods/webppl#551]
![image](https://cloud.githubusercontent.com/assets/6245103/16787114/9b9733d4-484e-11e6-8fd6-ee83879399ba.png)

When you run from the command line, it's a bit better:

```
false == true
    at /usr/local/lib/node_modules/webppl/src/dists.js:258

257|         var ps = ad.value(this.params.ps);
258|         assert.ok(ps.rank === 2);
     ---------------^
259|         assert.ok(ps.dims[1] === 1);

Stack trace:
    at makeDistributionType.sample (/usr/local/lib/node_modules/webppl/src/dists.js:258:16)
    at Object.env.coroutine.sample (/usr/local/lib/node_modules/webppl/src/header.js:58:24)
    at env.sample (/usr/local/lib/node_modules/webppl/src/header.js:78:26)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/webppl/src/main.js:222:10), <anonymous>:17:24)
    at /usr/local/lib/node_modules/webppl/src/util.js:51:13
    at /usr/local/lib/node_modules/webppl/src/util.js:14:14
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/webppl/src/main.js:222:10), <anonymous>:5:13)
    at /usr/local/lib/node_modules/webppl/src/main.js:222:48
    at Object.timeif (/usr/local/lib/node_modules/webppl/src/util.js:283:37)
    at Object.run (/usr/local/lib/node_modules/webppl/src/main.js:221:8)
```

**Comment by null-a** [comment]
Thanks for reporting this. I'm going to close this issue because I think it's a special case of #332, but it will definitely be useful to have this example to refer to.
