### ISSUE TITLE
OptimizeELBO - guidedGaussian test failed

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#605]
On 1c3cd24147bbeede50d42f24ab666d64a9ac41f9:

~~~~
Running "nodeunit:all" (nodeunit) task
Testing test-caching.js..............OK
Testing test-deterministic.js.................OK
Testing test-error-handling.js...OK
Testing test-examples.js..............OK
Random seed: 1393378568
Testing test-inference.js..............................................................................................................................................................................................................................................F..
>> OptimizeELBO - guidedGaussian
>> Message: Expected mean: -4, actual: -3.4735990233865213, tolerance: 0.2
>> Error: false == true
>> at Object.testWithinTolerance (tests/helpers/helpers.js:56:8)
>> at Object.testFunctions.mean (tests/test-inference.js:644:13)
>> at /Users/stuhlmueller/Projects/webppl/tests/test-inference.js:624:28
>> at Function._.each._.forEach (node_modules/underscore/underscore.js:158:9)
>> at Object.performTest (tests/test-inference.js:615:5)
>> at executeBound (node_modules/underscore/underscore.js:701:67)
>> at Object.bound (node_modules/underscore/underscore.js:733:14)
~~~~

**Comment by null-a** [comment]
Also [158225176](https://travis-ci.org/probmods/webppl/jobs/158225176).

**Comment by null-a** [comment]
We probably want to bump up the step size in the ELBO tests, after which we'll probably be able to reduce some of samples per step/steps/tolerance, which all seem quite high now I'm looking at it again.

**Comment by dorarad** [comment]
It may be a good idea to change the default in adam from 0.001 to 0.01. In experiments I've done so far 0.01 was consistently better..@null-a you changed the default in July from 0.1 to 0.001 (https://github.com/dritchie/adnn/commit/4f4dba21f498f929e5626876fa94d8ff78a3400c). Indeed 0.1 causes many cases of divergence, but I think 0.001 is too small..

**Comment by null-a** [comment]
@dorarad We also discussed this [here](https://github.com/probmods/webppl/issues/709#issuecomment-261751870).

**Comment by dorarad** [comment]
@paul right. Did you have a case in which 0.001 was better?

**Comment by jpchen** [comment]
I ran this ~10 times it seems to pass... `tol = 0.2` though, not sure if we're still looking to change the default step size?

**Comment by null-a** [comment]
Also [228774965](https://travis-ci.org/probmods/webppl/jobs/228774965).
