### ISSUE TITLE
Occasional "unrecognized node" error during CPS transform

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#814]
Example: https://travis-ci.org/probmods/webppl/jobs/219859137

~~~~
Error: [{"name":"_k214","loc":null,"type":"Identifier","comments":null,"typeAnnotation":null},{"callee":{"object":{"name":"_address61","loc":null,"type":"Identifier","comments":null,"typeAnnotation":null},"property":{"name":"concat","loc":null,"type":"Identifier","comments":null,"typeAnnotation":null},"computed":false,"loc":null,"type":"MemberExpression","comments":null},"arguments":[{"value":"_58","loc":null,"type":"Literal","comments":null,"regex":null}],"loc":null,"type":"CallExpression","comments":null},{"properties":[{"kind":"init","key":{"loc":{"start":{"line":59,"column":22},"end":{"line":59,"column":23},"source":"header.wppl"},"type":"Identifier","name":"a"},"value":{"loc":{"start":{"line":59,"column":25},"end":{"line":59,"column":26},"source":"header.wppl"},"type":"Identifier","name":"a"},"loc":null,"type":"Property","comments":null,"method":false,"shorthand":false,"computed":false,"decorators":null},{"kind":"init","key":{"loc":{"start":{"line":59,"column":28},"end":{"line":59,"column":29},"source":"header.wppl"},"type":"Identifier","name":"b"},"value":{"loc":{"start":{"line":59,"column":31},"end":{"line":59,"column":32},"source":"header.wppl"},"type":"Identifier","name":"b"},"loc":null,"type":"Property","comments":null,"method":false,"shorthand":false,"computed":false,"decorators":null}],"loc":null,"type":"ObjectExpression","comments":null}] does not match field "arguments": [Expression | SpreadElement] of type CallExpression
at add (node_modules/ast-types/lib/types.js:576:27)
at /home/travis/build/probmods/webppl/node_modules/ast-types/lib/types.js:589:17
at Array.forEach (native)
at value (node_modules/ast-types/lib/types.js:588:30)
at Object.callExpression (src/transforms/builders.js:23:22)
at buildCall (src/transforms/cps.js:24:16)
at /home/travis/build/probmods/webppl/src/transforms/cps.js:210:24
at loop (src/transforms/cps.js:173:14)
at /home/travis/build/probmods/webppl/src/transforms/cps.js:178:16
at /home/travis/build/probmods/webppl/src/transforms/cps.js:147:16
at loop (src/transforms/cps.js:173:14)
at /home/travis/build/probmods/webppl/src/transforms/cps.js:178:16
at /home/travis/build/probmods/webppl/src/transforms/cps.js:152:16
at Array.<anonymous> (src/transforms/cps.js:116:14)
at Array.<anonymous> (src/syntax.js:30:27)
at match (src/syntax.js:47:27)

span
Error: atomize: unrecognized node
at /home/travis/build/probmods/webppl/src/syntax.js:20:11
at match (src/syntax.js:52:10)
at atomize (src/transforms/cps.js:51:10)
at loop (src/transforms/cps.js:176:14)
at atomizeStar (src/transforms/cps.js:183:10)
at /home/travis/build/probmods/webppl/src/transforms/cps.js:205:20
at Array.<anonymous> (src/transforms/cps.js:116:14)
at Array.<anonymous> (src/syntax.js:30:27)
at match (src/syntax.js:47:27)
at atomize (src/transforms/cps.js:51:10)
at Array.<anonymous> (src/transforms/cps.js:204:18)
at Array.<anonymous> (src/syntax.js:30:27)
at match (src/syntax.js:47:27)
at cps (src/transforms/cps.js:202:14)
at Array.<anonymous> (src/transforms/cps.js:101:16)
at Array.<anonymous> (src/syntax.js:30:27)
~~~~

**Comment by null-a** [comment]
This appears to be another instance of #733, or at least related to that, so I'm closing this.
