### ISSUE TITLE
Backprop for unary derivatives fails for [1, 1] tensor

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#835]
This program using [webppl-nn](github.com/null-a/webppl-nn) fails:

```js
var mlp = stack([
  tanh,
  affine('mlp', { "in": 2, "out": 1 })
]);
        
var model = function() {
  var xs = param({ dims: [2, 1], name: 'xs' });
  var out = mlp(xs);
  factor(out);
  return out;
}

Optimize({
  model,
  steps: 10000
});
```
Error:

```
TypeError: Cannot read property '0' of undefined
    at model.wppl:409

408|
409| Optimize({
     ^
410|   model,

TypeError: Cannot read property '0' of undefined
    at Node.eval (eval at makeUnaryDerivatives (/usr/local/lib/node_modules/webppl/node_modules/adnn/ad/derivatives.js:18:12), <anonymous>:7:49)
    at Node.bw [as backward] (/usr/local/lib/node_modules/webppl/node_modules/adnn/ad/func.js:32:12)
    at Node.backpropRec (/usr/local/lib/node_modules/webppl/node_modules/adnn/ad/graph.js:37:8)
    at Node.backpropRec (/usr/local/lib/node_modules/webppl/node_modules/adnn/ad/graph.js:39:31)
    at Node.backpropRec (/usr/local/lib/node_modules/webppl/node_modules/adnn/ad/graph.js:39:31)
    at Node.ScalarNode.backprop (/usr/local/lib/node_modules/webppl/node_modules/adnn/ad/graph.js:76:7)
    at ELBO.<anonymous> (/usr/local/lib/node_modules/webppl/src/inference/elbo.js:88:35)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/webppl/src/main.js:252:25), <anonymous>:554:80)
    at /usr/local/lib/node_modules/webppl/src/util.js:38:13
    at /usr/local/lib/node_modules/webppl/src/main.js:198:14
```

By contrast, if we replace `mlp` with this, things work:

```js
var mlp = stack([
  function(x) { return Math.tanh(T.toScalars(x)[0]); },
  affine('mlp', { "in": 2, "out": 1 })
]);
```

**Comment by null-a** [comment]
I think the problem here is that the thing you're passing to `factor` isn't a scalar (or lifted scalar).

(Aside: With the most recent webppl-nn, you need to call e.g. `affine` on every execution of the model, not once at the top level as you have it here, in order for its parameters to be optimized.)

**Comment by stuhlmueller** [comment]
> I think the problem here is that the thing you're passing to `factor` isn't a scalar (or lifted scalar).

Thanks, that does seem to be the issue for the minimal example I gave. Things looks a bit different for my real model, but I'm probably also passing a `[1, 1]` tensor into some function that wants a scalar.

Our error messages are pretty uninformative in such cases, so this is difficult to debug. (Part of the difficulty here is that the error only happens during backprop, not during forward evaluation.)

> (Aside: With the most recent webppl-nn, you need to call e.g. `affine` on every execution of the model, not once at the top level as you have it here, in order for its parameters to be optimized.)

Ah, yes - this is correct for my real model, but I forgot about it above.
